### ISSUE TITLE
Social Login Flow

### ISSUE THREAD

**Issue by ruddell** [ruddell/generator-jhipster-ionic#16]
- [ ] Redirect the user on successful login back to the app (JHipster project - CustomSignInAdapter.java line 54) - this needs to work with both a regular JHipster-website user and the mobile user.
- [ ] If social login enabled, add a CORS proxy to sign in routes

Am I missing anything?

**Comment by abdulfousan** [comment]
+1
Yes you are right we need to work on both side(JHipster & ionic app).

**Comment by nsfreak** [comment]
I managed to do something similar, but client wasn't a mobile device, but a browser.

This are steps which I did:

1. Registered ProviderSignInInterceptor for ProviderSignInController
2. In "preSignIn" method I used requestCache (HttpSessionRequestCache) to save request.
3. In CustomSignInAdapter I used requestCache to retrieve request before user logged (from the step above) and returning actual URL of client

I am sure there is another way, but this is how I managed to do it... hope it helps
regards

**Comment by ruddell** [comment]
I've spent a lot of time trying to make Social Login work with JHipster but I'm at a dead end.  I can get it working in the browser but not on a device/emulator.  Some of the issues I've had include:
- Adding the app to Facebook/Google Authorized Domains
- Redirecting back to the application - not sure how this would work with a Cordova app

If no one has a solution, social login will just have to remain unsupported.

**Comment by othmanoss** [comment]
hi 
what if we add a `providerSignInControlle.setApplicationUrl("http://localhost:3000/").` in **SocialConfiguration**.
and in gulp add two proxy for **/signin** and **/social** .
else we can use half native

**Comment by ruddell** [comment]
Closing as this doesn't look like it will be happening
