### ISSUE TITLE
Session CSRF Token Issue

### ISSUE THREAD

**Issue by ruddell** [ruddell/generator-jhipster-ionic#17]
When running on an emulator and using **Session** as the Authentication choice, attempting to POST to any form results in a 403 error.  Chrome Remote Debugging tools give the following error: `"Invalid CSRF Token 'null' was found on the request parameter '_csrf' or header 'X-CSRF-TOKEN'."`

I assume this affect devices as well.

Related issue:
https://github.com/jhipster/generator-jhipster/issues/3498

Thanks to @vdham for reporting this

**Comment by ruddell** [comment]
I solved this by passing the CSRF-TOKEN as a header instead of part of a cookie when requesting from an Ionic app and storing it in localStorage.  Will PR and do a new release tonight.

**Comment by ruddell** [comment]
I'm going to manually test each option in an emulator in the morning.  I'll open a separate issue when I figure out what's going on (I think something with websockets, default apps work fine for me with master).

**Comment by vdham** [comment]
@ruddell ,

This has been tremendous help. I can see websocket connection working from android emulator after making PR 19 changes. 

Thanks.

**Comment by ruddell** [comment]
With the new release ([v2.1.3](https://github.com/ruddell/generator-jhipster-ionic/releases/tag/v2.1.3)), all authentication types work on emulators and with websockets.

Thanks again for bringing this to my attention! 😄
