### ISSUE TITLE
Error in tracker.service.js

### ISSUE THREAD

**Issue by rakeshkalra1983** [ruddell/generator-jhipster-ionic#22]
Hi 

I have a website running with jhipster v3.4.2 with web-sockets. When I generated ionic app using generator-jhipster-ionic and tried to login, I received error in tracer.server.js at line number 35:
```
authToken = angular.fromJson($localStorage.authenticationToken).access_token;
```
Figured out that $localStorage.authenticationToken is null, causing the error.

I have updated the code to look like below, but not sure if it is a proper solution: 
```
if($localStorage.authenticationToken!=null) {
            authToken = angular.fromJson($localStorage.authenticationToken).access_token;
}
```

**Comment by ruddell** [comment]
@rakeshkalra1983 Thank you for the feedback.  That was recently fixed the same way you did it via #20
