### ISSUE TITLE
Problem with CORS

### ISSUE THREAD

**Issue by lazaropj** [ruddell/generator-jhipster-ionic#24]
Hi everyone.

I'm with many problems to access a API from a microservice. 

I added a proxy on watching.js file 

```
var apiLazaro = url.parse('http://localhost:9000/primeirageracaomicroservice');
apiLazaro.route = '/primeirageracaomicroservice';
```

And added on middleware

`bsOptions.server.middleware = [proxy(apiProxy), proxy(oauthProxy), proxy(apiLazaro)];`

But I continue getting a CORS error

`XMLHttpRequest cannot load http://localhost:9000/primeirageracaomicroservice/api/pokemons/1?cacheBuster=1475333229380. Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values 'http://evil.com/, *', but only one is allowed. Origin 'http://localhost:3000' is therefore not allowed access.`

**Comment by ruddell** [comment]
You are correct though that it will initially result in a problem when trying to get data from a microservice.  The proxy currently only intercepts `/api` and `/oauth`.  For each microservice, you currently need to add a proxy as well.  Adding the following worked for me (using your service names):

```
var pokeApiProxy = url.parse('http://localhost:8080/primeirageracaomicroservice');
pokeApiProxy.route = '/primeirageracaomicroservice';
```
Note that the requests still go through the gateway, just to a prefixed API.  This is the normal JHipster microservice setup.  I'll see if there's a pattern that works for all microservices before I mark this fixed.

**Comment by lazaropj** [comment]
Hi @ruddell . Worked here. =D

Tks so much

watching.js file

```
var apiPrimeiraGeracao = url.parse('http://localhost:9000/primeirageracaomicroservice');
    apiPrimeiraGeracao.route = '/primeirageracaomicroservice';
```

`bsOptions.server.middleware = [proxy(apiProxy), proxy(oauthProxy), proxy(apiPrimeiraGeracao)];`

And one call

```
var promise = $http.get('primeirageracaomicroservice/api/pokemons?size=151', {
                    headers: {'Authorization': 'Bearer ' + token}
                });
                promise.then(function(retorno) {
                    vm.pokemons = retorno.data;
                })
                .catch(function(erro) {
                    alert(erro)
                });
```

Tks man
