### ISSUE TITLE
X-XSRF-TOKEN support

### ISSUE THREAD

**Issue by Mael-Brs** [ruddell/generator-jhipster-ionic#29]
Jhipster generator now use Spring CSRF default implementation (see : https://github.com/jhipster/generator-jhipster/commit/40e735c85238a885ce7dc63ce9c639b076f4b9fb).
The authentification feature is no longer working for the generated Ionic Apps.

**Comment by ruddell** [comment]
Yes the CSRF implementation changed in v3.10.0. I will be removing the option to generate apps using Seasion auth in the next version. Cookies and apps should not be used together

**Comment by Mael-Brs** [comment]
Hi Ruddell,
In my jhipster app, I should not use session auth to work with Ionic app ?

**Comment by ruddell** [comment]
Out of the available choices from JHipster (Session, JWT, UAA, Oauth2), this generator should work with JWT, UAA, and Oauth2.  

I recommend using JWT, but it is up to you.
